### ISSUE TITLE
Discussion: Does the JSON map fulfill its purpose?

### ISSUE THREAD

**Issue by keneanung** [IRE-Mudlet-Mapping/AchaeaCrowdmap#101]
We want our maintainers to upload a Mudlet JSON map as well. However, I don't think we use it for for diffs as they are often huge and the map diff comment is better suited in my opinion. Additionally, it doesn't always seem to reflect the actual map data in the binary file.

If we stop uploading it manually, we may be able to generate a JSON map file from the binary map and thus get rid of a manual step.

**Comment by vadi2** [comment]
Seems like a good idea!

**Comment by keneanung** [comment]
I'll work on this next as the binary map reader can now export Mudlet's JSON maps, if there are no objections.

**Comment by keneanung** [comment]
The JSON file is now automatically generated from the binary map file.
