### ISSUE TITLE
Buried JSON Data

### ISSUE THREAD

**Issue by NexusUnleashed** [IRE-Mudlet-Mapping/AchaeaCrowdmap#142]
This is perhaps a translation error in the JSON file creation. Some of the general data is appearing buried in the "Haila-ele" area userData (First image). Area continent lists, ferry rooms, mapping landmark rooms, etc. This data should likely be appearing under the top level userData object (Second image).
![2022-03-29_14-56-45](https://user-images.githubusercontent.com/18602482/160714215-219c1552-2e69-4552-a0d6-579e7e2ddd6a.jpg)
![2022-03-29_15-01-16](https://user-images.githubusercontent.com/18602482/160714416-1f74d932-3603-428c-bfbe-47680b4f8bdd.jpg)

**Comment by vadi2** [comment]
Intended as we use room 1 - before area/map userdata came along to Mudlet - to store data.
