### ISSUE TITLE
Pathing issues in Eleusis

### ISSUE THREAD

**Issue by ose-goetia** [IRE-Mudlet-Mapping/AchaeaCrowdmap#16]
While writing some scripts to navigate Eleusis I ran into a few bugs while using crowdmap. Here are the details:

42090 needs the south exit to be locked.
42092 needs the north exit to be locked.
42090 and 42092 both connect to each other via the special exit **push door**. 
_Comment: A directional exit and door is present there but it is locked and that's the only way in or out._

42100 and 42098 both connect to each other via the special exit **push gate**

6765's down exit should be set to 41875, but it is currently 13201.
_Comment: The up exit from 13201 is fine_

Thanks

**Comment by QwindorRousseau** [comment]
I will get the changes mapped in tonight and fix those exits. Just one of those things that changes and doesnt get fixed until someone says something unless I notice it in passing.

**Comment by QwindorRousseau** [comment]
Fixed with #18
