### ISSUE TITLE
[Suggestion] Allow special exits to prioritize over normal exits

### ISSUE THREAD

**Issue by ose-goetia** [IRE-Mudlet-Mapping/AchaeaCrowdmap#17]
As part of #16 I noticed that the special exit was not used until I locked the existing exits from 42090 and 42092. I suggest that special exits should possibly be considered first priority when it comes to determining the way to exit a room.

**Comment by ose-goetia** [comment]
This is not a crowdmap issue

**Comment by vadi2** [comment]
It is, you can give weights to exits. Some special exits take longer than normal so they can have a higher weight

**Comment by ose-goetia** [comment]
Then I will call this one a user error :)

**Comment by QwindorRousseau** [comment]
Again I can fix that with the other issue all in one and make sure it works like it should.

**Comment by QwindorRousseau** [comment]
Fixed wtih #18 . You can put an exit weight on the exit that doesn't work and the special exit will override it. Tested it with the Eleusis rooms and the the Den of the Quisalis and it works fine.
