### ISSUE TITLE
Temporary Unavailable Room

### ISSUE THREAD

**Issue by SlyViolin** [IRE-Mudlet-Mapping/AchaeaCrowdmap#187]
A plateau high in the mountains (60724, in Actar, the Valley of) -> worm warp -> In the shallows of Lake Muurn  (7988, in Muurn Lake)

60724 is locked with Merrywick availability. This wormhole does exist, but for the time being loops the player to the Cave. How should this be dealt with?

**Comment by ryanstadther** [comment]
I'm assuming the map realizes it moved to the cave automatically and correctly adjusts itself accordingly right away? If that is the case it is probably fine to leave it as is I would say...that room doesn't really lead to the rest of Actar, it leads to Merrywick, which is only open during December I presume...so it shouldn't really ever get used for pathing.

**Comment by SlyViolin** [comment]
No probs. Closing the issue.
