### ISSUE TITLE
Small room issues for repair

### ISSUE THREAD

**Issue by SlyViolin** [IRE-Mudlet-Mapping/AchaeaCrowdmap#189]
53005 - Inside the world tree.
ISSUE : Looping failure
(9 - send("embrace flame") mmp.customwalkdelay(10))
I cannot fathom the meaning of "send("embrace".

- Recommend re-visiting the spe link.
 **Fixed in Aster Keep, Ancyra, Aerinwild, Oh My! Update.**

**Comment by vadi2** [comment]
I think it's missing a `script:` prefix

**Comment by SlyViolin** [comment]
**FIXED IN ASTER KEEP, ANCYRA, AERINWILD, OH MY UPDATE.**
37067 - Fishing pier along the Pachacacha
Visual/code :  No exit exists to the west. Delete the link west to (1578)

**FIXED IN ASTER KEEP, ANCYRA, AERINWILD, OH MY UPDATE.**
10966 - A glittering mountainside
Visual issue : Map represents 10967 to the NW, Change it to present to the W.

**Comment by SlyViolin** [comment]
All three fixed in merged update. Verified on clean profile. Ready to close out!
