### ISSUE TITLE
Infinite weight exits in Hashan

### ISSUE THREAD

**Issue by ryanstadther** [IRE-Mudlet-Mapping/AchaeaCrowdmap#202]
Room 4497 and 4498 have the "infinite weight" checkbox ticked in Hashan, which basically prevents pathing through those exits. Not sure if this is intentional or not?

![image](https://user-images.githubusercontent.com/47157604/185709443-7fbb9168-f29e-4e98-bb5b-b46dbb93a099.png)

**Comment by vadi2** [comment]
None that I know of.

**Comment by SlyViolin** [comment]
These exits will be set to normal weight with the implementation of the Aster Keep, Ancyra, Aerinwild, Oh My! Update.

**Comment by SlyViolin** [comment]
Update merged, fix verified on clean profile! This can be closed out.
