### ISSUE TITLE
Petition : Room mark for Everglade

### ISSUE THREAD

**Issue by SlyViolin** [IRE-Mudlet-Mapping/AchaeaCrowdmap#237]
Petitioning the higher-ups to allow a roommark for the Everglade (pronoun changing rom) to be added to the crowdmap.

**Comment by keneanung** [comment]
Just add the mark name and room ID to https://github.com/IRE-Mudlet-Mapping/AchaeaCrowdmap/blob/development/danger/rules/allowed_room_marks.yaml in the same PR as you add the room mark in the map and you're good to go!

**Comment by keneanung** [comment]
Fixed with #240
