### ISSUE TITLE
Room marks to features

### ISSUE THREAD

**Issue by QwindorRousseau** [IRE-Mudlet-Mapping/AchaeaCrowdmap#35]
Placing this here as a reminder to myself to look into the feature system of the map that was implemented after the crowdmap was originally started in place of room marks.

**Comment by ryanstadther** [comment]
@QwindorRousseau  I was able to retrofit the migrate feature function used by Starmourn. Attached is a map with features all set up. Let me know what you think.

I set up a bunch of them GOTO FEATURE WILDERNESS, GOTO FEATURE HARBOUR, GOTO FEATURE BANK...for example.

See them all with FEATURE LIST (mapping mode on)

Also, I was able to steal a bit of other code and create this function. It will list out all rooms that have a feature (or multiple) assigned.

```
local m = {}
for r, _ in pairs(getRooms()) do
  for _, f in pairs(mmp.getRoomMapFeatures(r)) do
    m[f] = m[f] or {}
    m[f][#m[f]+1] = r
  end
end

if not next(m) then mmp.echo("This map has no features on it. Do mc on and feature create <feature> and then rcf <feature to add them!") return end

for f, rooms in pairs(m) do
  table.sort(rooms)
  echo('\n')
  mmp.echo("Rooms with the <"..mmp.settings.echocolour..">"..f.."<reset> feature:")
  for i = 1, #rooms do
      cecho(string.format("  <sea_green>%-5s<reset> %-35s <dim_grey>(in<reset> %s<dim_grey>)\n", rooms[i], getRoomName(rooms[i]), mmp.areatabler[getRoomArea(rooms[i])]))
  end
end
```

**Comment by ryanstadther** [comment]
[map.zip](https://github.com/IRE-Mudlet-Mapping/AchaeaCrowdmap/files/3933999/map.zip)

**Comment by QwindorRousseau** [comment]
That might be something you want to put into the mapper script. I put this here mainly because it was for the crowdmap for achaea that we were looking at possibly adding those.

**Comment by ryanstadther** [comment]
They are all added in the attached map in the comment above, check it out :)

**Comment by ryanstadther** [comment]
Map is for Achaea Crowd Map

**Comment by vadi2** [comment]
https://github.com/IRE-Mudlet-Mapping/AchaeaCrowdmap/pull/39
