### ISSUE TITLE
Check graphtage for JSON diffs

### ISSUE THREAD

**Issue by vadi2** [IRE-Mudlet-Mapping/AchaeaCrowdmap#60]
Would a tool like this be useful for diffs of the upcoming JSON map? https://github.com/trailofbits/graphtage

**Comment by ryanstadther** [comment]
This issue could probably be closed now that @keneanung worked his magic and got map diffs to show inline with PR comments....suuuper slick!

**Comment by vadi2** [comment]
It's still worthwhile, just to know how it compares to the map diffs - can't hurt to know. If it's the same or worse, we can dismiss it. @keneanung think you could plug it in?

**Comment by keneanung** [comment]
Sure. I'll put a workflow together. We can improve from there.

**Comment by keneanung** [comment]
I put something together. See the output at https://github.com/keneanung/CrowdmapTestRepo/pull/6#issuecomment-1012518693

I have 2 issues with this, but tl;dr I don't think this particular tool is useful to us:
1. I don't think that change is readable
2. Our map files are either too big or we trigger a similar issue to https://github.com/trailofbits/graphtage/issues/32 at least on my machine it hogged a core for quite a long time and the progress bar didn't move at all.

**Comment by vadi2** [comment]
Could we try with an real map diff? It's not obvious at first but then you do realise that key `1` was inserted

**Comment by keneanung** [comment]
https://github.com/keneanung/CrowdmapTestRepo/pull/6 now attempted a real map diff. However, the workflow timed out after 6 hours and seemingly didn't get anywhere.

I may have found an alternative way to get a semantic diff working. I'll change the workflow accordingly and report back.

**Comment by keneanung** [comment]
I implemented my other idea. It is a semi-structural diff, meaning it first sorts keys and arrays, then runs a textual diff. See https://github.com/keneanung/CrowdmapTestRepo/pull/6#issuecomment-1012518693 for the result.

The sorting of arrays may be slightly problematic as colours for example are arrays where the order of numbers is important. So we may miss changes there...

**Comment by ryanstadther** [comment]
this actually isn't too bad IMO

**Comment by vadi2** [comment]
Agreed, thanks for pushing on with the idea!

**Comment by keneanung** [comment]
All right, #111 updated and ready to go.
