### ISSUE TITLE
New Danger Rule - Room Marks

### ISSUE THREAD

**Issue by ryanstadther** [IRE-Mudlet-Mapping/AchaeaCrowdmap#81]
There should probably be a file in the repo that contains all the valid room marks to be used in a danger rule to ensure those are the only marks in the crowdmap. Currently the list only exists in the wiki...also if it were in the repo it could be tracked and reviewed if anything is changed.

Then if we wanted to add a new room mark it would have to be added to both the file and the map.

Wonder if this rule could check both ways? Compare the file to the map and vice versa? Not sure what would be best here.

**Comment by keneanung** [comment]
Fixed with #91
