### ISSUE TITLE
Restructure repository

### ISSUE THREAD

**Issue by keneanung** [IRE-Mudlet-Mapping/AchaeaCrowdmap#97]
Since the introduction of danger and the recent addition of the minified JSON map, we have a number of files that don't need to be published to GitHub pages or could be generated before publishing. I propose we restructure the repository a little to account for this.

I'd like to introduce a new default branch `development` similar to the current `gh-pages`, but with the static content for the webpage in a subdirectory. We could then have a GitHub action copy the map data on every commit to the default branch and generate additional content as well. Then we publish a subdirectory to the `gh-pages` branch, which will be the source for the website.

**Comment by vadi2** [comment]
That sounds good!
